[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
schema = { path = "../schema" }
eui = { path = "../../../eui/" }
env_logger = "*"
log = "0.4"
serialport = "4"
serde = "*"
postcard = { version = "1" }
anyhow = "*"