[package]
name = "ucat"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", default-features = false, features = ["derive"] }
postcard = { version = "1", features = ["experimental-derive"]  }
heapless = { version = "*", features = ["serde"] }
num_enum = { version = "0.7", default-features = false }
